### ISSUE TITLE
Add Shortcut for Speedtest CLI package

### ISSUE THREAD

**Issue by strausmann** [xmha97/chocolatey-coreteampackages#1]
Good Day, please add a shortcut into the windows Startmenu 

https://docs.chocolatey.org/en-us/create/functions/install-chocolateyshortcut

**Comment by xmha97** [comment]
In the future, you will be able to install this app with the start menu shortcut using the following command:
```
choco install speedtest --params "/StartMenuShortcut"
```

**Comment by xmha97** [comment]
I will keep this issue open until it is fixed.

**Comment by strausmann** [comment]
Ah, sorry. Had understood I had to use the parameter only.

**Comment by xmha97** [comment]
Done.
See [README.md](https://github.com/xmha97/chocolatey-coreteampackages/blob/main/automatic/speedtest/README.md)
